Veggies
Woolfson-Julia/project-team18 pull request #4
Opened 2024-10-19 02:49 UTC by TattiS

It's the first version of the veggies sections

2024-10-19 11:14 UTC, Woolfson-Julia requested changes
Молодец))
но есть небольшие правки)
На что обратить внимание.
1) добавь себе изменения с Гитхаба - писала в слек
2) не прописывай дополнительно размеры контейнера или секции, это прописано (смотри в слеке)
3) line-hight мы пишем не в рх. Округляем до 2 знаков после запятой, смотри правки.
4) Правильно li прописать через калькулятор как мы делали в дз. Размеры когда прописывали через calc. Но в целом и так правильно. Если получится будет отлично.
5) Есть пропущенные изменения маржинов нижних или текстовых характеристик, тебе все написала)

2024-10-19 11:14 UTC, Woolfson-Julia commented on src/css/vegetables.css
> +.veggies-section {
.veggies-section {
  background-color: #7a3145;
  тут только цвет фона оставь, все остальные стили прописаны в общих файлах css

2024-10-19 11:14 UTC, Woolfson-Julia commented on src/css/vegetables.css
> +.veggies-section-container {
.veggies-section-container { - удаляй, это не падинги, а точка перелома. Общие падинги я прописала) посмотри в слеке)
  padding-left: 20px;
  padding-right: 20px;

2024-10-19 11:14 UTC, Woolfson-Julia commented on src/css/vegetables.css
> +  line-height: 50px;
line-height: 1.04167; по макету, но мы окгругляем до 2 знаков после запятых.
line-height: 1.04; В рх мы не прописываем.
Исправь везде где есть line-height:

2024-10-19 11:14 UTC, Woolfson-Julia commented on src/css/vegetables.css
> +  text-transform: uppercase;
letter-spacing: -0.01em; - добавь - по макету есть

2024-10-19 11:14 UTC, Woolfson-Julia commented on src/css/vegetables.css
> +  font-family: 'Inter Tight';
[это ](font-family: 'Inter Tight';) - это удали, это у нас прописывается в общих стилях и так)

2024-10-19 11:14 UTC, Woolfson-Julia commented on src/css/vegetables.css
> +  font-style: normal;
font-style: normal; - это тоже удали)

2024-10-19 11:14 UTC, Woolfson-Julia commented on src/css/vegetables.css
> +  color: #fbfbfb;
Если у тебя белый цвет, то можешь его удалить.
он записывается и так в общих стилях
body {
  font-family: 'Inter Tight', sans-serif;
  color: #fbfbfb;
  background: #576f35;
}

2024-10-19 11:14 UTC, Woolfson-Julia commented on src/css/vegetables.css
> +  font-style: normal;
font-style: normal; - везде удали)

2024-10-19 11:14 UTC, Woolfson-Julia commented on src/partials/vegetables.html
> +          srcset="../img/Vegetables/eggplant@1x.png x1,../img/Vegetables/eggplant@2x.png 2x"
width="282" добавь всем изображениям

2024-10-19 11:14 UTC, Woolfson-Julia commented on src/css/vegetables.css
> +  max-height: 379px;
width: 100%; - тут и так оно будет на 100%. Можешь удалить
  max-width: 334px; - тут можно было бы оставить, но в целом я думаю там ошибка дизайнера, 1рх вряд ли разница. поэтому удаляй)
  max-height: 379px; - высоту мы н езадаем
  это можешь удалить

2024-10-19 11:14 UTC, Woolfson-Julia commented on src/css/vegetables.css
> +.veggies-section-card-image {
.veggies-section-card-image {
  /* width: 282px; */
  /* height: 243px; */
  max-width: 100%;
  height: auto;
  это все можно удалить. У нас ширина прописывается в html и все

2024-10-19 11:14 UTC, Woolfson-Julia commented on src/css/vegetables.css
> +    max-width: 768px;
.veggies-section {
    max-width: 768px; 
    это удаляй - это прописано в общих стилях у контейнера

2024-10-19 11:14 UTC, Woolfson-Julia commented on src/css/vegetables.css
> +  .veggies-section-container.container {
.veggies-section-container.container {
    max-width: 768px;
    padding-left: 32px;
    padding-right: 32px;
    
    это тоже все удаляй

2024-10-19 11:14 UTC, Woolfson-Julia commented on src/css/vegetables.css
> +    line-height: 64px;
line-height: 1;

2024-10-19 11:14 UTC, Woolfson-Julia commented on src/css/vegetables.css
> +    line-height: 20px;
line-height: 1.25;

2024-10-19 11:14 UTC, Woolfson-Julia commented on src/css/vegetables.css
> +  }
.veggies-section-card {
padding: 32px 30px;
у тебя для планшетной версии меняется падинги в карточке

2024-10-19 11:14 UTC, Woolfson-Julia commented on src/css/vegetables.css
> +    line-height: 1;
.veggies-section-card-text {
    margin-bottom: 10px; - у тебя меняетмя в планшетной версии. В мобильной было 14

2024-10-19 11:14 UTC, Woolfson-Julia commented on src/css/vegetables.css
> +  .veggies-section {
.veggies-section {
    max-width: 1280px;
  }
  удалить это прописано в общих правилах для контейнера

2024-10-19 11:14 UTC, Woolfson-Julia commented on src/css/vegetables.css
> +  .veggies-section-container.container {
.veggies-section-container.container {
    max-width: 1280px;
    padding-left: 100px;
    padding-right: 100px;
    удалить все
    это тоже все прописано

2024-10-19 11:14 UTC, Woolfson-Julia commented on src/css/vegetables.css
> +    flex-wrap: wrap;
justify-content: space-between;
 align-items: center; 
 Добавь это еще в этот класс

2024-10-19 11:14 UTC, Woolfson-Julia commented on src/css/vegetables.css
> +  }
.veggies-section-card {
        padding: 32px 32px;
        Добавь тут в дектопной версси другие падинги

2024-10-19 11:14 UTC, Woolfson-Julia commented on src/css/vegetables.css
> +  }
.veggies-section-list {
        column-gap: 21px;
.veggies-section-card-text {
    margin-bottom: 10px;

2024-10-20 06:45 UTC, TattiS commented on src/css/vegetables.css
> +.veggies-section-card-image {
Комментарии удалила. 
Для обсуждения -. veggies-section-card-image{
max-width: 100%;
height: auto;
} - эти правила обеспечивают "резиновость" картинок в промежутке 320px - 375px;

2024-10-20 11:15 UTC, Woolfson-Julia requested changes
Умничка, пару правок и готово))
Нужно убрать точки на всех путях по изображениям
Потом прописала тебе правильную формулу на расчет размера карточки, просто вставь себе мой вариант

2024-10-20 11:15 UTC, Woolfson-Julia commented on src/css/vegetables.css
> +.veggies-section-card-image {
Согласна)

2024-10-20 11:15 UTC, Woolfson-Julia commented on src/partials/vegetables.html
> +          srcset="../img/Vegetables/corn@1x.png x1,../img/Vegetables/corn@2x.png 2x" src="../img/Vegetables/corn@1x.png"
srcset="/img/Vegetables/corn@1x.png x1, /img/Vegetables/corn@2x.png 2x" src="/img/Vegetables/corn@1x.png"
Удвли везде где есть путь на изображение точки в начале.

Пример выше

2024-10-20 11:15 UTC, Woolfson-Julia commented on src/css/vegetables.css
> +    max-width: calc((100%-20px) / 2);
Исправь формулу на эту:
max-width: calc((724px - 20px) / 2);

2024-10-20 11:15 UTC, Woolfson-Julia commented on src/css/vegetables.css
> +  .veggies-section-card {
Исправь формулу н аэту:
.veggies-section-card {
    max-width: calc((1080px - 42px) / 3);

2024-10-20 14:40 UTC, Woolfson-Julia approved these changes

2024-10-20 14:41 UTC, merged